---
jobs:
  include:
    - stage: test
      sudo: required
      language: python
      python: "2.7"
      cache: pip
      services:
        - docker
      install:
        - pip install ansible
        - pip install docker
        - pip install molecule
      script: molecule test
      after_script:
        - molecule --version
        - ansible --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
