---
jobs:
  include:
    - stage: test
      sudo: required
      language: python
      python: "2.7"
      cache: pip
      services:
        - docker
      install:
        - pip install ansible
        - pip install docker
        - pip install molecule
        # extract dummy borg repo and mount it into a borg server container
        - tar xJf molecule/default/files/borgrepo.xz -C molecule/default/files
        - docker volume create borgrepo
        - docker run --rm -v borgrepo:/borgrepo-vol -v `pwd`/molecule/default/files/borgrepo/:/borgrepo-dir alpine sh -c 'cp -r /borgrepo-dir/* /borgrepo-vol/'
        # generate ssh keys for the borgrepo
        - ssh-keygen -f id_rsa -t rsa -N ''
        - mkdir -p /tmp/sshkeys/clients
        - mkdir /tmp/sshkeys/host
        - cp id_rsa.pub /tmp/sshkeys/clients/travisci
        - cp id_rsa.pub molecule/default/files/
        - cp id_rsa molecule/default/files/
        - sudo chown -R 1000:1000 /tmp/sshkeys
        # start borgserver
        - docker run -d --name borgserver -p 2222:22 -v borgrepo:/backup/travisci/borgrepo -v /tmp/sshkeys:/sshkeys nold360/borgserver
        - sleep 15
        # get the borg server's IP
        - export borg_server_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' borgserver | sed 's/\r//')
        # make it resolve where travis is running
        - ping -c 3 taskserver
        - sudo echo "${borg_server_ip} taskserver" >> /etc/hosts
        # populate the known_hosts file with borgserver's fingerprint
        - ssh-keyscan -H "${borg_server_ip}" > molecule/default/files/known_hosts
      script:
        - molecule --debug test
        # - export docker_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' borgserver)
        # - docker run --rm --add-host taskd.example.com:${docker_ip} -v `pwd`/molecule/default/client_files:/client_files:ro alpine sh -c "
        #   ping -c 3 taskd.example.com &&\
        #   apk --no-cache add task &&
        #   yes | task version &&
        #   yes | task config taskd.ca /client_files/ca.cert.pem &&
        #   yes | task config taskd.certificate /client_files/user.cert.pem &&
        #   yes | task config taskd.key /client_files/user.key.pem &&
        #   yes | task config taskd.server taskd.example.org:53589 &&
        #   yes | task config taskd.credentials -- My Org/user/$(cat /client_files/user-uuid) &&
        #   yes | task sync init"
      after_script:
        - molecule --version
        - ansible --version
        - docker logs borgserver

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
