---
jobs:
  include:
    - stage: test
      sudo: required
      language: python
      python: "2.7"
      cache: pip
      services:
        - docker
      install:
        - pip install ansible
        - pip install docker
        - pip install molecule
        # extract dummy borg repo and mount it into a borg server container
        - tar xJf molecule/default/files/borgrepo.xz -C molecule/default/files
        - docker volume create borgrepo
        - docker run --rm -v borgrepo:/borgrepo-vol -v `pwd`/molecule/default/files/borgrepo/:/borgrepo-dir alpine sh -c 'cp -r /borgrepo-dir/* /borgrepo-vol/'
        - ssh-keygen -f id_rsa -t rsa -N ''
        - mkdir -p /tmp/sshkeys/clients
        - mkdir /tmp/sshkeys/host
        - cp id_rsa.pub /tmp/sshkeys/clients/travisci
        - cp id_rsa.pub molecule/default/files/
        - cp id_rsa molecule/default/files/
        - sudo chown -R 1000:1000 /tmp/sshkeys
        - docker run --rm -v borgrepo:/repo alpine sh -c 'ls -clash /repo'
        - docker run -d --name borgserver -p 2222:22 -v borgrepo:/backup/travisci/ -v /tmp/sshkeys:/sshkeys nold360/borgserver
        - sleep 15
        - export borg_server_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' borgserver | sed 's/\r//')
        - echo ${borg_server_ip}
        - docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' borgserver
        # - ssh-keyscan -H -t rsa -p 2222 $(hostname -f) > molecule/default/files/known_hosts
        # - ssh-keyscan -H -p 2222 "${borg_server_ip}"
        - ssh-keyscan -H "${borg_server_ip}" > molecule/default/files/known_hosts
        # fingerprint with hostname
        # - ssh-keyscan -H -p 2222 "${borg_server_ip}" > molecule/default/files/known_hosts
        - ping -c 3 ${borg_server_ip}
        - cat molecule/default/files/known_hosts
        # and ip
        # - ssh-keyscan -H $(host `hostname -f` | awk '/has address/ { print $4 ; exit }') >> molecule/default/files/known_hosts
      script: molecule --debug test
      after_script:
        - molecule --version
        - ansible --version
        - docker logs borgserver
        - cat molecule/default/files/known_hosts
        - cat molecule/default/files/id_rsa
        - cat /tmp/sshkeys/clients/travisci
        - cat molecule/default/files/id_rsa.pub
        - ls -clash molecule/default/files/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
