---
- name: Refresh apt cache
  apt:
    update_cache: true
    cache_valid_time: 216000  # seconds; i.e. 1 day

- name: Ensure git is installed
  package:
    name: git
    state: present

- name: Clone taskd service repo
  git:
    repo: 'https://github.com/coaxial/docker-taskd-service'
    umask: '022'
    version: 'master'
    update: true
    dest: "{{ td__project_src }}"
  notify: start taskd

- name: Copy settings
  template:
    src: templates/taskserver.env.j2
    dest: "{{ td__project_src }}/taskserver/taskserver.env"
    owner: root
    group: root
    mode: '0600'
  notify:
    - start taskd
    - fetch client files

- name: Set hostname for taskd
  template:
    src: templates/docker-compose.hostname-override.yml.j2
    dest: "{{ td__project_src }}/docker-compose.hostname-override.yml"
  notify: start taskd

- name: Clone borgmatic service repo
  git:
    repo: 'https://github.com/coaxial/docker-borgmatic'
    version: 'snooze'
    umask: '022'
    update: true
    dest: "{{ td__borgmatic_project_src }}"
  notify: start borgmatic

- name: Copy borgmatic files
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ td__borgmatic_project_src }}/borgmatic/{{ item }}"
  with_items:
    - before-backup
    - after-backup
    - failed-backup
    - config.yaml
    - passphrase
  notify: start borgmatic

- name: Copy ssh files
  copy:
    src: "{{ item }}"
    dest: "{{ td__borgmatic_project_src }}/ssh/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  with_items:
    - id_rsa
    - id_rsa.pub
    - known_hosts

- name: Extend borgmatic compose file
  template:
    src: templates/docker-compose.data-vol.yml.j2
    dest: "{{ td__borgmatic_project_src }}/docker-compose.data-vol.yml"
  notify: start borgmatic
