---
- name: Stop taskserver
  docker_service:
    project_src: "{{ td__project_src}}"
    state: absent
  notify: start taskd

- name: Check if Borgmatic is running for taskserver
  command: "docker ps --filter 'name=borgmatic' --format={% raw %}'{{.Names}}'{% endraw %}"
  register: borgmatic_containers
  changed_when: false
  failed_when: false

- name: Stop borgmatic
  docker_service:
    project_src: "{{ td__borgmatic_project_src }}"
    state: present
    stopped: true
  when: borgmatic_containers.stdout | regex_search("taskserver")
  notify: start borgmatic

- name: Create restore volume
  docker_volume:
    name: taskddata_restore

- name: Get latest backup
  docker_container:
    image: alpine
    name: fetch-backup
    volumes:
      - "{{ td__borgmatic_project_src }}/ssh/:/root/.ssh/:ro"
      - "{{ td__borgmatic_project_src}}/borgmatic/passphrase:/root/passphrase:ro"
      - taskddata_restore:/backup
    command: >
      /bin/sh -c "
      apk --no-cache add borgbackup openssh-client &&
      cd /backup &&
      export BORG_REMOTE_PATH=borg1 &&
      export BORG_PASSCOMMAND='cat /root/passphrase' &&
      borg list --short --last 1 {{ td__borg_url }} &&
      borg list --short --last 1 {{ td__borg_url }} | xargs -I '{}' borg extract --sparse --strip-components 2 {{ td__borg_url }}::'{}'
      "
    cleanup: true
    detach: false

- name: Restore data
  docker_container:
    image: alpine
    name: restore-backup
    volumes:
      - taskddata_restore:/backup
      - "{{ td__taskdata_volname }}:/target"
    command: /bin/sh -c 'rm -rf /target/* && cp -r /backup/* /target'
    cleanup: true
    detach: false

- name: REMOVEME debug
  docker_container:
    image: alpine
    name: debug
    volumes:
      - "{{ td__taskdata_volname }}:/restored:ro"
    command: /bin/sh -c 'apk --no-cache add tree && tree /restored'
    cleanup: true
    detach: false

- name: Remove volume
  docker_volume:
    name: taskddata_restore
    state: absent
