---
- name: Converge
  hosts: all
  vars:
    td__fqdn: taskd.example.org
    td__orgname: 'My Org'
    td__cert_organization: 'test cert org'
    td__cert_country: 'CA'
    td__cert_state: 'ON'
    td__cert_locality: 'Toronto'
    td__borg_url: borg@taskserver:borgrepo
    td__borg_passphrase: s3cur3

  roles:
    - role: ansible-role-taskserver
